export const LOAD_PLAYER_RECORDS = 'app/PlayerRecordsPage/LOAD_PLAYER_RECORDS';
export const LOAD_PLAYER_RECORDS_SUCCESS = 'app/PlayerRecordsPage/LOAD_PLAYER_RECORDS_SUCCESS';
export const LOAD_PLAYER_RECORDS_ERROR = 'app/PlayerRecordsPage/LOAD_PLAYER_RECORDS_ERROR';
